install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop bucket add extras
  - ps: scoop install visualc rktools2k3
build_script:
  - cmd: cl fastlist.cpp
test_script:
  - cmd: bench 100