install:
  - ps: if ((Get-Command scoop -ErrorAction SilentlyContinue) -eq $null) { iex (new-object net.webclient).downloadstring('https://get.scoop.sh') }
  - ps: scoop bucket add extras
  - ps: scoop update *
  - ps: scoop install visualc rktools2k3
build_script:
  - cmd: cl fastlist.cpp
test_script:
  - cmd: tasklist
  - cmd: fastlist
  - cmd: bench 100
cache:
  - '%USERPROFILE%\scoop\cache'